version: 3
tasks:
  prettier:
    - yarn prettier -w ./src
  build:
    - sudo sh -c "/usr/bin/echo 3 > /proc/sys/vm/drop_caches"
    - sudo yarn build
  start:
    - sudo systemctl start nginx
    - sudo systemctl status nginx
  stop:
    - sudo systemctl stop nginx
    - sudo systemctl status nginx
  status:
    - sudo systemctl status nginx
  docker:
    cmds:
      - yarn build
      - docker build -t yhc0818/insta-pic-web-app:latest .
      - docker run -d -p 80:80 yhc0818/insta-pic-web-app
  deploy:
    cmds:
      - yarn build
      - docker build -t yhc0818/insta-pic-web-app:latest --platform linux/amd64 .
      - docker push yhc0818/insta-pic-web-app:latest